# Generated by Django 4.2.7 on 2023-12-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5, null=True),
        ),
    ]
