# Generated by Django 4.2.7 on 2023-12-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='prioritize',
            field=models.IntegerField(default=0),
        ),
    ]
