# Generated by Django 4.2.7 on 2023-12-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_parent_task_task_prioritize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='prioritize',
        ),
    ]
